### ISSUE TITLE
A motto was pending approval and added to inbox simultaneously -- likely due to an edit scenario

### ISSUE THREAD

**Issue by madi-vh** [dwrss/MottoBotto#122]
Scenario:

Madi writes a motto. There's a typo, she starts to edit. Matt nominates motto. The nomination goes through (and has the pending emoji added), then the edit is saved, and the inbox emoji is added. Should double check the motto was actually added. Motto here: https://discord.com/channels/833842753799848016/833854270544805928/836393857734279189

**Comment by benbacardi** [comment]
Can't reproduce!
