### ISSUE TITLE
Disable emoji mottos

### ISSUE THREAD

**Issue by kirknorthrop** [dwrss/MottoBotto#28]
Disable mottos containing emoji, @person, #channel

**Comment by izzystardust** [comment]
If the bot responds in Discord with an embed, it won't notify the mentioned people - that's an alternative to preventing them altogether.
https://discord.com/developers/docs/resources/channel#embed-object, https://discordpy.readthedocs.io/en/stable/api.html#embed

**Comment by madi-vh** [comment]
We disabled mottos with @person and emoji-only mottos, but handled #channel separately. Emoji are allowed as part of a motto, but cannot make up the full motto.
