### ISSUE TITLE
DM bot to turn on/off nickname auto-update feature

### ISSUE THREAD

**Issue by kirknorthrop** [dwrss/MottoBotto#31]
Change your name by messaging the bot. Requires an Airtable change to stop updating display names after the users sends a new name

**Comment by madi-vh** [comment]
Closing as won’t do. We realized users may not understand why their name doesn’t auto update after they use this command.

**Comment by madi-vh** [comment]
Backtracking. We’ve decided this is okay if we have MottoBotto confirm with the user that they understand this will turn off auto-updates on their nick name and they will have to send such updates manually in future.

**Comment by madi-vh** [comment]
Name should default to username. 
If a user opts in with `!nick on`, next time they are encountered by the bot, we use their nick. We should message them with details on what this will do, and how to turn it off.
If they then opt out with `!nick off` we immediately remove their nick from Airtable and go back to just using their username. We should message in this scenario as well, informing them that their nickname has been deleted and we will use their username, and how to turn it back on.
