### ISSUE TITLE
Create a checkbox column in the AirTable to allow for easy moderation. 

### ISSUE THREAD

**Issue by madi-vh** [dwrss/MottoBotto#57]
Checkbox will allow us and/or mod team to Allow/Disallow mottos. If checkbox is checked, motto will show on the public view. If not checked, it will not show. This allows us to remove spam, bad mottos, and such.

**Comment by RosemaryOrchard** [comment]
Done! The column is hidden in the published view, and there's an additional editor view for "Unmoderated"
